[build]
  functions = "netlify/functions"
  environment = { TEMPLATE_OVERVIEW_PATH = "templates/template-overview.html", TEMPLATE_CARD_PATH = "templates/template-card.html", TEMPLATE_PRODUCT_PATH = "templates/template-product.html" }
